apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-1
  namespace: nm-3
spec:
  hard:
    requests.memory: 1Gi
    limits.memory: 1Gi


#kubectl apply -f [ns-resource-quota].yaml --namespace=[mynamespace]